### ISSUE TITLE
Bot Cooldown

### ISSUE THREAD

**Issue by matthew-robertson** [matthew-robertson/banned-word-tracker#3]
As a user/admin, if someone mentions vore and it spawns a conversation on the topic, I don't want the bot to spam dozens of messages. After a mention, the bot should not post a reset message for 15 minutes or so (do keep updating/resetting the counter though).

**Comment by matthew-robertson** [comment]
@barsquiggle Does this address the issue you were having? The bot currently has a predefined cool-down of 30 minutes, but I could expedite this feature for you if you want.

**Comment by barsquiggle** [comment]
Everything is fixed with it now! I'm not quite sure what was wrong
(possibly something to do with the timestamping/time calculation?) but
another lucky reboot and it's functional now. Thanks so much for replying!

On Wed, Jul 25, 2018 at 7:53 PM, Matthew Robertson <notifications@github.com
