### ISSUE TITLE
Bot detects random thing as the banned word

### ISSUE THREAD

**Issue by no-boot-device** [matthew-robertson/banned-word-tracker#64]
Sending `||*||` will cause the bot to trigger. We have not edited the bot's functionality as far as I can tell, and yet it seems to trigger and say this word is "vore".

**Comment by matthew-robertson** [comment]
After some testing and discussion on Discord, it's been determined that this is caused by an issue in the underlying Confusables library. A PR to fix that has been submitted.

Once that's accepted, this ticket will be resolved when I bump the version number to the new version.
